name: Nix qmk env
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "flake.lock"
      - "firmware/*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
          - os: macos-latest
            target: aarch64-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Install nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup | Install cachix
        uses: cachix/cachix-action@v12
        with:
          name: edeneast-qmk-firmware
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build | Environment
        run: nix build --accept-flake-config .#devShells.${{ matrix.target }}.default
